#!/usr/bin/env bash
# Blue-green helpers for ma3 behind Caddy (remote side).
# Sourced/inlined by deploy.sh; can also be run via:
#   ssh host 'bash -s' < deploy/common/bluegreen_remote.sh
#
# Required env (set by caller):
#   REMOTE_DIR, UVICORN_HOST, HEALTHZ_TIMEOUT, REQUIRE_VECTOR
#   BLUE_GREEN_PORT_A (default 8000), BLUE_GREEN_PORT_B (default 8001)
#   CADDY_UPSTREAM_FILE, CADDY_RELOAD_CMD
# Optional:
#   BLUE_GREEN_DRAIN_SEC (default 5) — wait after Caddy switch before stopping old
#   BLUE_GREEN_PUBLIC_SMOKE_URL — if set, curl /healthz on public URL after switch
set -euo pipefail

bluegreen_state_dir() {
  echo "${REMOTE_DIR}/data/bluegreen"
}

bluegreen_ports() {
  BLUE_GREEN_PORT_A="${BLUE_GREEN_PORT_A:-8000}"
  BLUE_GREEN_PORT_B="${BLUE_GREEN_PORT_B:-8001}"
  if [[ "${BLUE_GREEN_PORT_A}" == "${BLUE_GREEN_PORT_B}" ]]; then
    echo "FATAL: BLUE_GREEN_PORT_A and BLUE_GREEN_PORT_B must differ" >&2
    return 1
  fi
}

bluegreen_detect_active() {
  bluegreen_ports
  local state_dir active_file
  state_dir="$(bluegreen_state_dir)"
  active_file="${state_dir}/active_port"
  mkdir -p "${state_dir}"

  if [[ -f "${active_file}" ]]; then
    local recorded
    recorded="$(tr -d '[:space:]' <"${active_file}")"
    if [[ "${recorded}" == "${BLUE_GREEN_PORT_A}" || "${recorded}" == "${BLUE_GREEN_PORT_B}" ]]; then
      if curl -sf "http://127.0.0.1:${recorded}/healthz" >/dev/null 2>&1; then
        echo "${recorded}"
        return 0
      fi
    fi
  fi

  # Prefer whichever slot is healthy; default to A if neither responds.
  if curl -sf "http://127.0.0.1:${BLUE_GREEN_PORT_A}/healthz" >/dev/null 2>&1; then
    echo "${BLUE_GREEN_PORT_A}"
    return 0
  fi
  if curl -sf "http://127.0.0.1:${BLUE_GREEN_PORT_B}/healthz" >/dev/null 2>&1; then
    echo "${BLUE_GREEN_PORT_B}"
    return 0
  fi
  echo "${BLUE_GREEN_PORT_A}"
}

bluegreen_idle_for() {
  bluegreen_ports
  local active="$1"
  if [[ "${active}" == "${BLUE_GREEN_PORT_A}" ]]; then
    echo "${BLUE_GREEN_PORT_B}"
  else
    echo "${BLUE_GREEN_PORT_A}"
  fi
}

bluegreen_write_upstream() {
  local port="$1"
  local upstream="${CADDY_UPSTREAM_FILE:?CADDY_UPSTREAM_FILE required}"
  mkdir -p "$(dirname "${upstream}")"
  local tmp
  tmp="${upstream}.tmp.$$"
  cat >"${tmp}" <<EOF
# Generated by ma3 blue-green deploy — do not edit by hand during a cutover.
# Active uvicorn: 127.0.0.1:${port}
reverse_proxy 127.0.0.1:${port}
EOF
  mv -f "${tmp}" "${upstream}"
}

bluegreen_reload_caddy() {
  local cmd="${CADDY_RELOAD_CMD:?CADDY_RELOAD_CMD required}"
  echo "==> caddy reload: ${cmd}"
  # shellcheck disable=SC2086
  eval ${cmd}
}

bluegreen_wait_health() {
  local port="$1"
  local ready=0
  local deadline=$((SECONDS + HEALTHZ_TIMEOUT))
  local health_json="/tmp/ma3-healthz-${port}.json"
  while ((SECONDS < deadline)); do
    if curl -sf "http://127.0.0.1:${port}/healthz" >"${health_json}" 2>/dev/null; then
      if [[ "${REQUIRE_VECTOR}" != "1" ]]; then
        ready=1
        break
      fi
      local feats
      feats="$(python3 -c "import json;print(','.join(json.load(open('${health_json}')).get('features',[])))")"
      if [[ "${feats}" == *vector* ]]; then
        ready=1
        break
      fi
    fi
    sleep 2
  done
  if [[ "${ready}" -ne 1 ]]; then
    echo "healthz not ready on :${port} after ${HEALTHZ_TIMEOUT}s" >&2
    tail -40 "/tmp/ma3-v1-uvicorn-${port}.log" 2>/dev/null >&2 || true
    return 1
  fi
  cp -f "${health_json}" /tmp/ma3-healthz.json
  python3 -m json.tool /tmp/ma3-healthz.json
}

bluegreen_start_uvicorn() {
  local port="$1"
  local env_file="${REMOTE_DIR}/ma3.env"
  cd "${REMOTE_DIR}/code/server"
  set -a
  # shellcheck disable=SC1090
  source "${env_file}"
  set +a
  unset MA3_DISABLE_EMBEDDINGS || true
  # Stop a leftover process on the idle slot (failed prior attempt).
  pkill -f "uvicorn app.main:app.*--port ${port}" 2>/dev/null || true
  sleep 1
  nohup .venv/bin/python -m uvicorn app.main:app \
    --host "${UVICORN_HOST}" --port "${port}" --app-dir . \
    >"/tmp/ma3-v1-uvicorn-${port}.log" 2>&1 &
  echo $! >"${REMOTE_DIR}/ma3.pid"
  echo "started uvicorn pid=$(cat "${REMOTE_DIR}/ma3.pid") port=${port}"
}

bluegreen_stop_port() {
  local port="$1"
  pkill -f "uvicorn app.main:app.*--port ${port}" 2>/dev/null || true
}

# Full cutover: start idle → health → write upstream → reload caddy → drain → stop old.
bluegreen_cutover() {
  bluegreen_ports
  local state_dir active idle drain
  state_dir="$(bluegreen_state_dir)"
  mkdir -p "${state_dir}"
  active="$(bluegreen_detect_active)"
  idle="$(bluegreen_idle_for "${active}")"
  drain="${BLUE_GREEN_DRAIN_SEC:-5}"

  echo "==> blue-green: active=:${active} → idle=:${idle}"
  bluegreen_start_uvicorn "${idle}"
  bluegreen_wait_health "${idle}"

  bluegreen_write_upstream "${idle}"
  bluegreen_reload_caddy

  if [[ -n "${BLUE_GREEN_PUBLIC_SMOKE_URL:-}" ]]; then
    echo "==> public smoke ${BLUE_GREEN_PUBLIC_SMOKE_URL}/healthz"
    local ok=0 i
    for i in $(seq 1 30); do
      if curl -sf "${BLUE_GREEN_PUBLIC_SMOKE_URL}/healthz" >/dev/null; then
        ok=1
        break
      fi
      sleep 1
    done
    [[ "${ok}" -eq 1 ]] || {
      echo "FATAL: public healthz failed after switch; rolling Caddy back to :${active}" >&2
      bluegreen_write_upstream "${active}"
      bluegreen_reload_caddy || true
      bluegreen_stop_port "${idle}"
      return 1
    }
  fi

  echo "==> drain ${drain}s then stop old :${active}"
  sleep "${drain}"
  bluegreen_stop_port "${active}"
  echo "${idle}" >"${state_dir}/active_port"
  echo "${idle}" >"${state_dir}/last_cutover_port"
  date -u +%Y-%m-%dT%H:%M:%SZ >"${state_dir}/last_cutover_at"
  echo "==> blue-green cutover complete; live=:${idle}"
}

bluegreen_status() {
  bluegreen_ports
  local state_dir active_file
  state_dir="$(bluegreen_state_dir)"
  active_file="${state_dir}/active_port"
  echo "port_a=${BLUE_GREEN_PORT_A} port_b=${BLUE_GREEN_PORT_B}"
  echo -n "recorded_active="
  if [[ -f "${active_file}" ]]; then cat "${active_file}"; else echo "(none)"; fi
  echo -n "detected_active="; bluegreen_detect_active
  echo -n "a_health="; curl -sf "http://127.0.0.1:${BLUE_GREEN_PORT_A}/healthz" >/dev/null && echo ok || echo down
  echo -n "b_health="; curl -sf "http://127.0.0.1:${BLUE_GREEN_PORT_B}/healthz" >/dev/null && echo ok || echo down
  if [[ -n "${CADDY_UPSTREAM_FILE:-}" && -f "${CADDY_UPSTREAM_FILE}" ]]; then
    echo "upstream_file=${CADDY_UPSTREAM_FILE}"
    grep -E 'reverse_proxy|^#' "${CADDY_UPSTREAM_FILE}" || true
  fi
}

# Allow: status | cutover (when executed as a script with COMMAND=)
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  : "${REMOTE_DIR:?}"
  UVICORN_HOST="${UVICORN_HOST:-127.0.0.1}"
  HEALTHZ_TIMEOUT="${HEALTHZ_TIMEOUT:-240}"
  REQUIRE_VECTOR="${REQUIRE_VECTOR:-1}"
  cmd="${1:-status}"
  case "${cmd}" in
  status) bluegreen_status ;;
  cutover) bluegreen_cutover ;;
  *)
    echo "usage: $0 status|cutover" >&2
    exit 2
    ;;
  esac
fi
